MA-16212: add cli interface
VKCOM/create-vk-mini-app pull request #133
Opened 2024-01-25 09:25 UTC by pasha-nikitin-2003

2024-01-29 07:28 UTC, nshvyryaev commented on src/helpers/getProjectName.ts
> +  return targetDir === '.' ? path.basename(path.resolve()) : targetDir;
Или, как вариант, в сообщение про "Current directory" в src/prompts/needOverwrite.ts вывести первые 3-4 файла или папки из текущей директории, чтобы пользователь понял, о какой папке речь

2024-02-02 10:05 UTC, nshvyryaev approved these changes

2024-02-02 10:17 UTC, nshvyryaev approved these changes

2024-02-05 09:03 UTC, evg-evdokimov requested changes

2024-02-05 09:03 UTC, evg-evdokimov commented on src/prompts/getLang.ts
> +          title: langColor(lang.name),
```suggestion
        return {
          title: lang.color(lang.name),
```

есть причина создавать отдельную переменную здесь?

2024-02-05 09:29 UTC, pasha-nikitin-2003 commented on src/helpers/pipePrompts.ts
> +      if (!newConfig) return;
Да, если мы ловим ошибку на каком то из этапов опроса, то мы считаем, что не можем создать мини-апп, выводим ошибку, и завершаем скрипт

2024-02-05 09:44 UTC, pasha-nikitin-2003 commented on src/helpers/pipePrompts.ts
> +    for (let fn of fns) {
Это и есть reduce, просто [слышал](https://stackoverflow.com/questions/41243468/javascript-array-reduce-with-async-await) что для асинхронных операций лучше использовать обычные циклы.

2024-02-05 11:00 UTC, evg-evdokimov approved these changes

2024-02-05 11:05 UTC, merged